answer_space = {"action": ["NONE",
                           "moving",
                           "opening",
                           "closing",
                           "turning on",
                           "turning off",
                           "putting",
                           "slicing",
                           "breaking",
                           "making",
                           "cleaning",
                           "using up",
                           "filling",
                           "emptying",
                           "throwing",
                           "thrown",
                           "pushing",
                           "tidying",
                           # "move",
                           # "close",
                           # "open",
                           # "slice",
                           # "turn on",
                           # "turn off",
                           # "break",
                           # "make",
                           # "put",
                           # "throw",
                           # "fill",
                           # "use up",
                           # "empty",
                           # "clean",
                           # "tidy",
                           # "push",
                           ],
                "subjects": ['NONE',
                             'books',
                             'plants',
                             'spray bottle',
                             'remote control',
                             'tomato slice',
                             'bathtub',
                             'plunger',
                             'chair',
                             'bread',
                             'bowl',
                             'tennis racket',
                             'ladle',
                             'dumbbell',
                             'tomato',
                             'bread slice',
                             'scrub brush',
                             'vase',
                             'paper towel',
                             'laundry hamper',
                             'lettuce slice',
                             'hand towel holder',
                             'toilet',
                             'table top decor',
                             'pepper shaker',
                             'potato slice',
                             'dog bed',
                             'faucet',
                             'teddy bear',
                             'pencil',
                             'target circle',
                             'pen',
                             'watering can',
                             'tissue box',
                             'plate',
                             'shower door',
                             'credit card',
                             'bed',
                             'watch',
                             'sofa',
                             'side table',
                             'blinds',
                             'window',
                             'curtains',
                             'alarm clock',
                             'book',
                             'sink',
                             'pan',
                             'boots',
                             'basket ball',
                             'wine bottle',
                             'kettle',
                             'dish sponge',
                             'shower curtain',
                             'stove burner',
                             'poster',
                             'ottoman',
                             'fork',
                             'toilet paper hanger',
                             'paper towel roll',
                             'house plant',
                             'television',
                             'shelving unit',
                             'lettuce',
                             'footstool',
                             'apple slice',
                             'cell phone',
                             'phone',
                             'room decor',
                             'desktop',
                             'key chain',
                             'mirror',
                             'coffee table',
                             'statue',
                             'salt shaker',
                             'potato',
                             'light switch',
                             'bottle',
                             'newspaper',
                             'soap bar',
                             'stove knob',
                             'tv stand',
                             'desk lamp',
                             'pot',
                             'toaster',
                             'pillow',
                             'arm chair',
                             'knife',
                             'sink basin',
                             'shower glass',
                             'cloth',
                             'apple',
                             'baseball bat',
                             'cup',
                             'box',
                             'dining table',
                             'spatula',
                             'floor',
                             'candle',
                             'counter top',
                             'drawer',
                             'shower head',
                             'microwave',
                             'floor lamp',
                             'fridge',
                             'cd',
                             'towel',
                             'aluminum foil',
                             'vacuum cleaner',
                             'mug',
                             'garbage can',
                             'coffee machine',
                             'garbage bag',
                             'egg',
                             'butter knife',
                             'bathtub basin',
                             'dresser',
                             'desk',
                             'cabinet',
                             'safe',
                             'soap bottle',
                             'toilet paper',
                             'egg cracked',
                             'painting',
                             'towel holder',
                             'hand towel',
                             'spoon',
                             'laptop',
                             'stool',
                             'shelf',
                             'table'],
                "prep": ["NONE",
                         "on",
                         "in",
                         "next to",
                         "to",
                         "to break",
                         "to hit",
                         "out of",
                         "near",
                         "with"],
                "objects": ['NONE',
                            'books',
                            'plants',
                            'spray bottle',
                            'remote control',
                            'tomato slice',
                            'bathtub',
                            'plunger',
                            'chair',
                            'bread',
                            'bowl',
                            'tennis racket',
                            'ladle',
                            'dumbbell',
                            'tomato',
                            'bread slice',
                            'scrub brush',
                            'vase',
                            'paper towel',
                            'laundry hamper',
                            'lettuce slice',
                            'hand towel holder',
                            'toilet',
                            'table top decor',
                            'pepper shaker',
                            'potato slice',
                            'dog bed',
                            'faucet',
                            'teddy bear',
                            'pencil',
                            'target circle',
                            'pen',
                            'watering can',
                            'tissue box',
                            'plate',
                            'shower door',
                            'credit card',
                            'bed',
                            'watch',
                            'sofa',
                            'side table',
                            'blinds',
                            'window',
                            'curtains',
                            'alarm clock',
                            'book',
                            'sink',
                            'pan',
                            'boots',
                            'basket ball',
                            'wine bottle',
                            'kettle',
                            'dish sponge',
                            'shower curtain',
                            'stove burner',
                            'poster',
                            'ottoman',
                            'fork',
                            'toilet paper hanger',
                            'paper towel roll',
                            'house plant',
                            'television',
                            'shelving unit',
                            'lettuce',
                            'footstool',
                            'apple slice',
                            'cell phone',
                            'phone',
                            'room decor',
                            'desktop',
                            'key chain',
                            'mirror',
                            'coffee table',
                            'statue',
                            'salt shaker',
                            'potato',
                            'light switch',
                            'bottle',
                            'newspaper',
                            'soap bar',
                            'stove knob',
                            'tv stand',
                            'desk lamp',
                            'pot',
                            'toaster',
                            'pillow',
                            'arm chair',
                            'knife',
                            'sink basin',
                            'shower glass',
                            'cloth',
                            'apple',
                            'baseball bat',
                            'cup',
                            'box',
                            'dining table',
                            'spatula',
                            'floor',
                            'candle',
                            'counter top',
                            'drawer',
                            'shower head',
                            'microwave',
                            'floor lamp',
                            'fridge',
                            'cd',
                            'towel',
                            'aluminum foil',
                            'vacuum cleaner',
                            'mug',
                            'garbage can',
                            'coffee machine',
                            'garbage bag',
                            'egg',
                            'butter knife',
                            'bathtub basin',
                            'dresser',
                            'desk',
                            'cabinet',
                            'safe',
                            'soap bottle',
                            'toilet paper',
                            'egg cracked',
                            'painting',
                            'towel holder',
                            'hand towel',
                            'spoon',
                            'laptop',
                            'stool',
                            'shelf',
                            'table'],
                "state": ['NONE',
                          'black',
                          'blue',
                          'brown',
                          'clean',
                          'cleaned',
                          'close',
                          'closed',
                          'coffee',
                          'broken',
                          'complete',
                          'dirty',
                          'empty',
                          'full',
                          'glass',
                          'gray',
                          'green',
                          'marble',
                          'metal',
                          'nothing',
                          'off',
                          'open',
                          'opened',
                          'plastic',
                          'pottery',
                          'purple',
                          'red',
                          'silver',
                          'sliced',
                          'tile',
                          'transparent',
                          'pink',
                          'water',
                          'white',
                          'wine',
                          'wood',
                          'yellow',
                          'gold',
                          'ceramic',
                          'orange'],
                "yes/no": ["NONE",
                           "yes",
                           "no",
                           "unanswerable"],
                "order": ["NONE",
                          "former",
                          "latter"],
                "number": ['NONE',
                           '0',
                           '1',
                           '2',
                           '3',
                           '4',
                           '5',
                           '6',
                           '7',
                           '8',
                           '9',
                           '10',
                           '11',
                           '12',
                           '13',
                           '14']}